# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Hibbiki.Chromium
PackageVersion: 133.0.6943.54
InstallerType: exe
InstallModes:
- silent
UpgradeBehavior: install
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
ReleaseDate: 2025-02-05
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/Hibbiki/chromium-win64/releases/download/v133.0.6943.54-r1402768/mini_installer.sync.exe
  InstallerSha256: A83E0A9232358D202F08DF8B947959D0AEB7E127D98957F07E0843599875A48A
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/Hibbiki/chromium-win64/releases/download/v133.0.6943.54-r1402768/mini_installer.sync.exe
  InstallerSha256: A83E0A9232358D202F08DF8B947959D0AEB7E127D98957F07E0843599875A48A
  InstallerSwitches:
    Custom: --system-level
ManifestType: installer
ManifestVersion: 1.9.0
