# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Hibbiki.Chromium
PackageVersion: 133.0.6943.54
PackageLocale: en-US
Publisher: The Chromium Authors
PublisherUrl: https://github.com/Hibbiki/chromium-win64
Author: Hibbiki
PackageName: Chromium
PackageUrl: https://github.com/Hibbiki/chromium-win64
License: BSD 3-Clause License
LicenseUrl: https://chromium.googlesource.com/chromium/src.git/+/refs/heads/master/LICENSE
Copyright: Copyright 2015 The Chromium Authors. All rights reserved.
CopyrightUrl: https://chromium.googlesource.com/chromium/src.git/+/refs/heads/master/LICENSE
ShortDescription: Stable Chromium build for Windows 64-bit, nothing fancy.
Tags:
- browser
- chromium
ReleaseNotes: 7c3040a609fdc1a3bfa27da091501f1142233798 ../out/x64/mini_installer.sync.exe 87c99e7f72590f9eb9ea1dafa37b8a4497bb06af ../out/x64/chrome.sync.7z 87ccf2ea165330e7554ad74d7e77c1292337d952 ../out/x64/mini_installer.nosync.exe 5c148372191a4117c5cfd55f6a86b69cb9e6b4a1 ../out/x64/chrome.nosync.7z fab27c3c4d4a78a6a516fbbc347bc0ea53d8dd36 ../out/noarch/policy_templates.zip
ReleaseNotesUrl: https://github.com/Hibbiki/chromium-win64/releases/tag/v133.0.6943.54-r1402768
ManifestType: defaultLocale
ManifestVersion: 1.9.0
