# Created using wingetcreate 1.9.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: DavidSungaila.SUBSTitute
PackageVersion: 3.0.2.0
Platform:
- Windows.Universal
- Windows.Desktop
MinimumOSVersion: 10.0.22621.0
InstallerType: msix
PackageFamilyName: 42088DavidSungaila.426978D2B4847_jpcc5wdckvw3p
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/sungaila/SUBSTitute/releases/download/v3.0.2/SUBSTitute_3.0.2.0.msixbundle
  InstallerSha256: 753F9AB261C2ECD9BC04B5F72D6C9271D92A9EBFA9964EBC46276E36CB37CD60
  SignatureSha256: D1027E311AF2204D9C0202F3A3BC0A6240FD2BC40873F5B9F557334FEF91D4E5
- Architecture: arm64
  InstallerUrl: https://github.com/sungaila/SUBSTitute/releases/download/v3.0.2/SUBSTitute_3.0.2.0.msixbundle
  InstallerSha256: 753F9AB261C2ECD9BC04B5F72D6C9271D92A9EBFA9964EBC46276E36CB37CD60
  SignatureSha256: D1027E311AF2204D9C0202F3A3BC0A6240FD2BC40873F5B9F557334FEF91D4E5
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2024-12-21
