# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: prefix-dev.pixi
PackageVersion: 0.41.0
InstallerLocale: en-US
InstallerType: wix
InstallerSwitches:
  Custom: -norestart
UpgradeBehavior: install
ProductCode: '{2C5CD060-49F2-4BFA-99EE-EDE59887AFB8}'
ReleaseDate: 2025-02-05
AppsAndFeaturesEntries:
- Publisher: pixi contributors
  UpgradeCode: '{D983A0B8-0183-4F99-BA13-A1C49BD8E46F}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/prefix-dev/pixi/releases/download/v0.41.0/pixi-x86_64-pc-windows-msvc.msi
  InstallerSha256: ED2929C27AF5F1226298AD3E834B02F4D893A01579746D6249B740C867DDA627
ManifestType: installer
ManifestVersion: 1.9.0
