# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: prefix-dev.pixi
PackageVersion: 0.41.0
PackageLocale: en-US
Publisher: prefix-dev
PublisherUrl: https://pixi.sh
PublisherSupportUrl: https://github.com/prefix-dev/pixi/issues
Author: pixi contributors
PackageName: pixi
PackageUrl: https://github.com/prefix-dev/pixi
License: BSD-3-Clause
LicenseUrl: https://github.com/prefix-dev/pixi/blob/HEAD/LICENSE
Copyright: Copyright (c) 2023, prefix.dev GmbH
CopyrightUrl: https://github.com/prefix-dev/pixi/blob/main/LICENSE
ShortDescription: A cross-platform, multi-language package manager and workflow tool
Moniker: pixi
Tags:
- conda
- conda-environment
- conda-packages
- hacktoberfest
- package-management
- package-manager
- package-manager-tool
- python-virtual-environment
- rust
- rust-lang
ReleaseNotes: |-
  Release Notes
  ✨ Highlights
  This release introduces lazily creating solve environments for the pypi-dependencies resulting in a significant speed-up for environments that only depend on wheels. If you want to force the use of wheels you can now also set no-build in the pypi-options table. To test this you can now just use pixi lock to create a lockfile without installing an environment.
  Added
  - Add pixi lock by @Hofer-Julian in #3061 and #3064
  - Add no-build to pypi-options by @tdejager in #2997
  Changed
  - Lazily initiate solve environments for pypi-dependencies by @nichmor and @tdejager in #3029
  - Use Github Releases /latest for self-update and prompt on downgrades by @jaimergp in #2989
  - Set PS1 in shell-hook too by @jaimergp in #2991
  - Prevent line-based 3-way merge on pixi.lock by @ChristianRothQC in #3019
  - Auto-prepend 'v' to version numbers during pixi installation by @m-naumann in #3000
  - Parse labels and related errors from build backend by @baszalmstra in #2952
  Documentation
  - Enable autocomplete on Zsh by @ywilke in #3009
  - Add section on aws codeartifact by @rayduck in #3020
  - Add pixi-diff documentation by @pavelzw in #3025
  - Fix python tutorial by @ruben-arts in #3035
  Fixed
  - Always show cursor after control+c by @ruben-arts in #2635
  - mirrors configuration follows correct priority by @ruben-arts in #3002
  - Don't check requires python in satisfiability by @ruben-arts in #2968
  - Enforce recompile trampoline by @Hofer-Julian in #3013
  - project platform remove by @Hofer-Julian in #3017
  - Lockfile not invalidated when we remove platforms by @Hofer-Julian in #3027
  - Will also update prefix if there are pypi path dependencies by @tdejager in #3034
  - Initialize rayon late and use uv from tag by @baszalmstra in #2957
  - Change back to multithreaded runtime by @tdejager in #3041
  - Logic was backward for creating missing .bashrc by @hjmjohnson in #3051
  - Do proper sanity check on add and run by @ruben-arts in #3054
  - Add check error message to remove uv dependencies by @Dozie2001 in #3052
  Refactor
  - Make diff module public by @pavelzw in #3010
  - Enforce no unwrap via clippy by @Hofer-Julian in #3006
  - Improve AuthenticationStorage, update rattler by @pavelzw in #2909
  Removed
  - Remove description from pixi init template by @Hofer-Julian in #3012
  New Contributors
  - @Dozie2001 made their first contribution in #3052
  - @hjmjohnson made their first contribution in #3051
  - @m-naumann made their first contribution in #3000
  - @ChristianRothQC made their first contribution in #3019
  - @rayduck made their first contribution in #3020
  - @ywilke made their first contribution in #3009
  Download pixi 0.41.0
  File Platform Checksum
  pixi-aarch64-apple-darwin.tar.gz Apple Silicon macOS checksum
  pixi-x86_64-apple-darwin.tar.gz Intel macOS checksum
  pixi-aarch64-pc-windows-msvc.zip ARM64 Windows checksum
  pixi-aarch64-pc-windows-msvc.msi ARM64 Windows checksum
  pixi-x86_64-pc-windows-msvc.zip x64 Windows checksum
  pixi-x86_64-pc-windows-msvc.msi x64 Windows checksum
  pixi-aarch64-unknown-linux-musl.tar.gz ARM64 MUSL Linux checksum
  pixi-x86_64-unknown-linux-musl.tar.gz x64 MUSL Linux checksum
ReleaseNotesUrl: https://github.com/prefix-dev/pixi/releases/tag/v0.41.0
ManifestType: defaultLocale
ManifestVersion: 1.9.0
