# Created with YamlCreate.ps1 v2.4.3 $debug=NVS1.LF.7-4-6.Unix
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Mozilla.SeaMonkey
PackageVersion: 2.53.20
PackageLocale: en-US
Publisher: The SeaMonkey Council
PublisherUrl: https://www.seamonkey-project.org/
PublisherSupportUrl: https://www.seamonkey-project.org/community#support
PrivacyUrl: https://www.seamonkey-project.org/legal/privacy
Author: The SeaMonkey Council
PackageName: SeaMonkey
PackageUrl: https://www.seamonkey-project.org/
License: MPL-2.0
LicenseUrl: https://www.seamonkey-project.org/legal/#license
# Copyright:
# CopyrightUrl:
ShortDescription: The SeaMonkey project is a community effort to develop the SeaMonkey Internet Application Suite.
# Description:
Moniker: seamonkey
Tags:
- browser
- cross-platform
- foss
- gecko
- open-source
- web-browser
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.9.0
