# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: BurakKOSE.WinoMail
PackageVersion: 1.8.7.0
PackageLocale: en-US
Publisher: Burak KÖSE
PublisherUrl: https://github.com/bkaankose
PublisherSupportUrl: https://github.com/bkaankose/Wino-Mail/issues
PackageName: Wino Mail
PackageUrl: https://github.com/bkaankose/Wino-Mail
License: GPL-3.0
ShortDescription: Built-in Mail & Calendars app clone for Windows.
Tags:
- csharp
- dotnet
- fluent-design
- gmail
- imap
- mail
- outlook
- uwp
- windows
- xaml
ReleaseNotesUrl: https://github.com/bkaankose/Wino-Mail/releases/tag/v1.8.7
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/bkaankose/Wino-Mail/wiki
ManifestType: defaultLocale
ManifestVersion: 1.9.0
