# Created with komac v2.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Tutanota.Tutanota
PackageVersion: 261.250116.0
PackageLocale: en-US
Publisher: Tutao GmbH
PublisherUrl: https://tuta.com/
PublisherSupportUrl: https://github.com/tutao/tutanota/issues
Author: Tutao GmbH
PackageName: Tutanota Desktop
PackageUrl: https://github.com/tutao/tutanota
License: GPL-3.0
LicenseUrl: https://github.com/tutao/tutanota/blob/HEAD/LICENSE.txt
Copyright: Copyright © 2022 Tutao GmbH
ShortDescription: Tutanota is an email client with a strong focus on security and privacy that lets you encrypt emails on all your devices.
Description: |-
  Tutanota is the worlds most secure email service, easy to use and private by design.
  With end-to-end encryption and 2FA, your emails have never been more secure.
  The built-in encryption guarantees that your mailbox belongs to you.
  Nobody can decrypt or read your data.
Moniker: tutanota
Tags:
- calendar
- email
- email-client
- encryption
- end-to-end-encryption
- privacy
- private
- secure
ReleaseNotes: |-
  Bugfixes
  - Fix unexpected error during signup for paid account #8272
  - Fix not authorized error after login #8267
  - "Search has been disabled" + Settings reverting to default, due to Windows app improper shut down of multiple windows #8281
  - New emails don't appear in the inbox if the inbox is in view #8277
  - LabelsPopup "Apply" button label does not use translation #8273
  - NotFoundError  404:  DELETE /rest/tutanota/calendarevent #8262
  Milestone
  Asset Checksums (SHA256)
  tutanota-desktop-linux.AppImage:
  6247ebedfab6cdd97141b3c67de8e73c9a3774e2a3dc55d6cdb9a1f13abf4c7ftutanota-desktop-win.exe:
  9a8198f01ab2bb6c189a6bf26fc0e2b6d40b5f5fa82947797c70a51214ae099dtutanota-desktop-mac.dmg:
  25eae6df28a08e6c7b797e506e9b56f313050822eac0ac20316db92b9e77739e
ReleaseNotesUrl: https://github.com/tutao/tutanota/releases/tag/tutanota-desktop-release-261.250116.0
PurchaseUrl: https://tutanota.com/pricing
Documentations:
- DocumentLabel: FAQ
  DocumentUrl: https://tutanota.com/faq
ManifestType: defaultLocale
ManifestVersion: 1.9.0
