# Created with komac v2.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Tutanota.Tutanota
PackageVersion: 261.250116.0
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ReleaseDate: 2025-01-17
AppsAndFeaturesEntries:
- DisplayName: "Tuta Mail 261.250116.0\x03肁"
  Publisher: Tutao GmbH
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/tutao/tutanota/releases/download/tutanota-desktop-release-261.250116.0/tutanota-desktop-win.exe
  InstallerSha256: 9A8198F01AB2BB6C189A6BF26FC0E2B6D40B5F5FA82947797C70A51214AE099D
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/tutao/tutanota/releases/download/tutanota-desktop-release-261.250116.0/tutanota-desktop-win.exe
  InstallerSha256: 9A8198F01AB2BB6C189A6BF26FC0E2B6D40B5F5FA82947797C70A51214AE099D
  InstallerSwitches:
    Custom: /ALLUSERS
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.9.0
