# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: kkonradpl.XDR-GTK
PackageVersion: "1.2"
PackageLocale: en-US
Publisher: kkonradpl
PublisherUrl: https://github.com/kkonradpl
PublisherSupportUrl: https://github.com/kkonradpl/xdr-gtk/issues
PackageName: XDR-GTK
PackageUrl: https://github.com/kkonradpl/xdr-gtk
License: GPL-2.0
ShortDescription: User interface for radio tuner control (XDR-F1HD, TEF668X)
ReleaseNotesUrl: https://github.com/kkonradpl/xdr-gtk/releases/tag/v1.2
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/kkonradpl/xdr-gtk/wiki
ManifestType: defaultLocale
ManifestVersion: 1.9.0
