# Created using wingetcreate 1.9.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: irusanov.ZenTimings
PackageVersion: "1.35"
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ZenTimings.exe
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/irusanov/ZenTimings/releases/download/v1.35/ZenTimings_v1.35.zip
  InstallerSha256: E5763913A14BD3927BABDACB83D16F97289FAD22A0B7E56BDEF0D9738CBE45F8
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-01-10
