# Created using wingetcreate 1.9.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: irusanov.ZenTimings
PackageVersion: "1.35"
PackageLocale: en-US
Publisher: irusanov
PublisherUrl: https://github.com/irusanov
PublisherSupportUrl: https://github.com/irusanov/ZenTimings/issues
PackageName: ZenTimings
PackageUrl: https://github.com/irusanov/ZenTimings
License: GPL-3.0
ShortDescription: A free, simple and lightweight app for monitoring memory timings on Ryzen platform.
Tags:
- amd
- amd-cpu
- ddr4
- overclock
- ryzen
- timings
ReleaseNotesUrl: https://github.com/irusanov/ZenTimings/releases/tag/v1.35
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/irusanov/ZenTimings/wiki
ManifestType: defaultLocale
ManifestVersion: 1.9.0
