# Created with YamlCreate.ps1 v2.3.4 Dumplings Mod $debug=QUSU.CRLF.7-4-1.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Ryujinx.Ryujinx.Ava
PackageVersion: 1.1.1242
InstallerType: zip
ReleaseDate: 2024-03-22
Installers:
- Architecture: x64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: publish/Ryujinx.Ava.exe
  InstallerUrl: https://github.com/Ryujinx/release-channel-master/releases/download/1.1.1242/test-ava-ryujinx-1.1.1242-win_x64.zip
  InstallerSha256: BF227B944471389BE2705BE0DBE543E84846A1AB7403321AD22E190F0D089DDF
ManifestType: installer
ManifestVersion: 1.6.0
