# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: AlexandruCsete.Gpredict
PackageVersion: 2.3.37
PackageLocale: en-US
Publisher: Alexandru Csete
PackageName: Gpredict
License: Proprietary
ShortDescription: Real time satellite tracking and orbit prediction.
ManifestType: defaultLocale
ManifestVersion: 1.9.0
