# Created with komac v2.9.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Microsoft.UpdateAssistant
PackageVersion: 1.4.19041.2183
Platform:
- Windows.Desktop
InstallerType: exe
Scope: machine
InstallerSwitches:
  Silent: ' '
  SilentWithProgress: ' '
ProductCode: '{D5C69738-B486-402E-85AC-2456D98A64E4}'
ReleaseDate: 2022-10-18
Installers:
- Architecture: x86
  InstallerUrl: https://download.microsoft.com/download/4/8/3/483976ae-b4b1-490d-bd5f-74fdc44bb84e/Windows10Upgrade9252.exe
  InstallerSha256: C0424D0AE06CA1E6E0249B40D33AC40D74075856D543EC0924884664FBA52B79
ManifestType: installer
ManifestVersion: 1.9.0
