# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Ivirius.IviriusTextEditor
PackageVersion: 4.0.0.264
PackageLocale: en-US
Publisher: Ivirius
PublisherUrl: https://github.com/IviriusMain
PublisherSupportUrl: https://github.com/IviriusMain/Ivirius-Text-Editor/issues
PackageName: Ivirius Text Editor
PackageUrl: https://github.com/IviriusMain/Ivirius-Text-Editor
License: MIT
ShortDescription: Rich text editing tool similar to WordPad
ReleaseNotesUrl: https://github.com/IviriusMain/Ivirius-Text-Editor/releases/tag/4.0.0.264
ManifestType: defaultLocale
ManifestVersion: 1.9.0
