# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: JeniusApps.Nightingale
PackageVersion: 4.4.3.0
PackageLocale: en-US
Publisher: Jenius Apps
PublisherUrl: https://github.com/jenius-apps
PublisherSupportUrl: https://github.com/jenius-apps/nightingale-rest-api-client/issues
PackageName: Nightingale REST Client
PackageUrl: https://github.com/jenius-apps/nightingale-rest-api-client
License: MIT
ShortDescription: A modern, resource-efficient REST API client for Windows.
Tags:
- csharp
- dotnet
- nightingale-rest-client
- restapi
- uwp
- windows10
- windows11
- winui
- xaml
ReleaseNotesUrl: https://github.com/jenius-apps/nightingale-rest-api-client/releases/tag/v4.4.3
ManifestType: defaultLocale
ManifestVersion: 1.9.0
