# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: JeniusApps.Nightingale
PackageVersion: 4.4.3.0
Platform:
- Windows.Universal
- Windows.Desktop
MinimumOSVersion: 10.0.18362.0
InstallerType: msix
PackageFamilyName: 43891JeniusApps.NightingaleRESTAPIClient_jaj7tphbgjeh8
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/jenius-apps/nightingale-rest-api-client/releases/download/v4.4.3/Nightingale_4.4.3.0_x64_ARM64.msixbundle
  InstallerSha256: 3431D7E94CC74E2ECC0773DEFD8AFD988C17C4C41F62F7D35D89299C5C656B82
  SignatureSha256: E3F8013922EA3A29691C527E5332E986F16C4456B5DD6AEAF7B0EC6734F2724B
- Architecture: arm64
  InstallerUrl: https://github.com/jenius-apps/nightingale-rest-api-client/releases/download/v4.4.3/Nightingale_4.4.3.0_x64_ARM64.msixbundle
  InstallerSha256: 3431D7E94CC74E2ECC0773DEFD8AFD988C17C4C41F62F7D35D89299C5C656B82
  SignatureSha256: E3F8013922EA3A29691C527E5332E986F16C4456B5DD6AEAF7B0EC6734F2724B
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2024-03-14
