# Created with YamlCreate.ps1 v2.4.3 $debug=QUSU.LF.7-4-6.Unix
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: HeidiSQL.HeidiSQL
PackageVersion: 12.9.0.6999
PackageLocale: en-US
Publisher: Ansgar Becker
PublisherUrl: https://www.anse.de/
PublisherSupportUrl: https://www.heidisql.com/help.php
# PrivacyUrl:
Author: Ansgar Becker
PackageName: HeidiSQL
PackageUrl: https://www.heidisql.com/
License: GPL-2.0-or-later
LicenseUrl: https://github.com/HeidiSQL/HeidiSQL/blob/master/LICENSE
Copyright: Copyright (c) 2000-2023 Ansgar Becker
CopyrightUrl: https://github.com/HeidiSQL/HeidiSQL/blob/master/out/license.txt
ShortDescription: A lightweight client for managing MariaDB, MySQL, SQL Server, PostgreSQL and SQLite, written in Delphi
# Description:
Moniker: heidisql
Tags:
- sql
- sql-client
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.9.0
