# Created with komac v2.9.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: ppy.osu
PackageVersion: 2025.118.3
PackageLocale: en-US
Publisher: ppy Pty Ltd
PublisherUrl: https://ppy.sh/
PublisherSupportUrl: https://github.com/ppy/osu/issues
PrivacyUrl: https://osu.ppy.sh/legal/en/Privacy
Author: ppy Pty Ltd
PackageName: osu!
PackageUrl: https://osu.ppy.sh/
License: MIT
LicenseUrl: https://github.com/ppy/osu/raw/master/LICENCE
Copyright: Copyright (c) 2024 ppy Pty Ltd
CopyrightUrl: https://osu.ppy.sh/legal/en/Copyright
ShortDescription: rhythm is just a *click* away!
Description: |-
  A free-to-win rhythm game. Rhythm is just a click away!

  This is the future – and final – iteration of the osu! game client which marks the beginning of an open era! Currently
  known by and released under the release codename "lazer". As in sharper than cutting-edge.
Moniker: osu!
Tags:
- beatmap-parser
- game
- osu
- rhythm
ReleaseNotes: |-
  Just a 'lil hotfix, with android this time!Editor
  Fix crash from new combo colour selector when there are no combo colours present (ppy/osu#31616 by @bdach)
  Reliability
  Fix discord error messages popping up constantly (ppy/osu#31640 by @frenzibyte)
  Discord seems to have broken something. Until it's fixed we're just going to hide the messages as to not bother you peoples.Fix potential crash when adjusting offset (ppy/osu#31644 by @peppy)
  Gameplay
  Make offset adjust more lenient (ppy/osu#31645 by @peppy)
  We added new rules to disallow changing offset too far into gameplay, but it wasn't accounting for intro time correctly. Now it does, so you have a full 10 seconds to adjust.(you can also always adjust during breaks)Tooling
  Fix android builds not building (ppy/osu#31633 by @bdach)
  Full Changelog: https://github.com/ppy/osu/compare/2025.118.2...2025.118.3
ReleaseNotesUrl: https://github.com/ppy/osu/releases/tag/2025.118.3
Documentations:
- DocumentLabel: Upgrading to lazer
  DocumentUrl: https://osu.ppy.sh/wiki/en/Help_centre/Upgrading_to_lazer
ManifestType: defaultLocale
ManifestVersion: 1.9.0
