# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: shefer.ferrpad
PackageVersion: 1.0.0.0
PackageLocale: en-US
Publisher: shefer
PublisherUrl: https://github.com/shef3r
PublisherSupportUrl: https://github.com/shef3r/ferrpad/issues
PackageName: ferrpad
PackageUrl: https://github.com/shef3r/ferrpad
License: Proprietary
ShortDescription: a UWP text editor for WIndows 10/11.
ReleaseNotesUrl: https://github.com/shef3r/ferrpad/releases/tag/1.0
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/shef3r/ferrpad/wiki
ManifestType: defaultLocale
ManifestVersion: 1.9.0
