# Created with komac v2.9.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Microsoft.OpenJDK.21
PackageVersion: 21.0.6.7
MinimumOSVersion: 10.0.0.0
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: ADDLOCAL=FeatureMain,FeatureEnvironment,FeatureJarFileRunWith,FeatureJavaHome
UpgradeBehavior: uninstallPrevious
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://aka.ms/download-jdk/microsoft-jdk-21.0.6-windows-x64.msi#winget
  InstallerSha256: 5886C09E68EE2A8EBC0529AFF76600D9644DCE5190773D2EE01FEA1E4636DE57
  ProductCode: '{72589493-6DC5-4B68-81B4-E3897E04A2C7}'
- Architecture: arm64
  InstallerUrl: https://aka.ms/download-jdk/microsoft-jdk-21.0.6-windows-aarch64.msi#winget
  InstallerSha256: 0B664AA355DCC8573795780E1488328A2A613ECA566F9C4EF3C9471CF19FD82A
  ProductCode: '{5F2C1FE4-9BBD-41C3-9365-AB47CCA13231}'
ManifestType: installer
ManifestVersion: 1.9.0
