# Created with YamlCreate.ps1 v2.4.3 $debug=QUSU.LF.7-2-6.Unix
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: DuckStudio.GitHubView.Nightly
PackageVersion: 2025.01.19.12849721517
PackageLocale: zh-CN
Publisher: 鸭鸭「カモ」
PublisherUrl: https://duckduckstudio.github.io/yazicbs.github.io/
PublisherSupportUrl: https://github.com/DuckDuckStudio/GitHubView/issues
# PrivacyUrl:
Author: 鸭鸭「カモ」
PackageName: GitHubView
PackageUrl: https://github.com/DuckDuckStudio/GitHubView/
License: GNU General Public License v3.0
LicenseUrl: https://github.com/DuckDuckStudio/GitHubView/blob/master/LICENSE.txt
Copyright: 版权所有 (c) 鸭鸭「カモ」
CopyrightUrl: https://github.com/DuckDuckStudio/GitHubView/blob/master/LICENSE.txt
ShortDescription: "\U0001F4BB在控制台中查看GitHub上的内容"
Description: GitHubView 是一个用于查看 GitHub 上的信息的命令行工具。
# Moniker:
Tags:
- cli
- github
- nightly
- 信息查看
- 命令
- 命令工具
- 命令行工具
- 控制台
- 终端
- 终端工具
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
Documentations:
- DocumentLabel: README
  DocumentUrl: https://github.com/DuckDuckStudio/GitHubView/blob/master/README.md
- DocumentLabel: 贡献指南
  DocumentUrl: https://github.com/DuckDuckStudio/GitHubView/blob/master/CONTRIBUTING.md
ManifestType: defaultLocale
ManifestVersion: 1.9.0
