# Created with YamlCreate.ps1 v2.4.3 $debug=QUSU.LF.7-2-6.Unix
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.9.0.schema.json

PackageIdentifier: DuckStudio.GitHubView.Nightly
PackageVersion: 2025.01.19.12849721517
PackageLocale: en-US
Publisher: 鸭鸭「カモ」
PublisherUrl: https://duckduckstudio.github.io/yazicbs.github.io/
PublisherSupportUrl: https://github.com/DuckDuckStudio/GitHubView/issues
# PrivacyUrl:
Author: 鸭鸭「カモ」
PackageName: GitHubView
PackageUrl: https://github.com/DuckDuckStudio/GitHubView/
License: GNU General Public License v3.0
LicenseUrl: https://github.com/DuckDuckStudio/GitHubView/blob/master/LICENSE.txt
Copyright: Copyright (c) 鸭鸭「カモ」
CopyrightUrl: https://github.com/DuckDuckStudio/GitHubView/blob/master/LICENSE.txt
ShortDescription: "\U0001F4BBViewing content on GitHub in your console"
Description: GitHubView is a command line tool for viewing content on GitHub.
# Moniker:
Tags:
- cli
- command
- command-line
- command-line-tool
- commandlinetool
- console
- console-tool
- consoletool
- github
- information-view
- nightly
- terminal-tool
- tool
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
Documentations:
- DocumentLabel: README
  DocumentUrl: https://github.com/DuckDuckStudio/GitHubView/blob/master/README.md
- DocumentLabel: Contribution Guide
  DocumentUrl: https://github.com/DuckDuckStudio/GitHubView/blob/master/CONTRIBUTING.md
ManifestType: locale
ManifestVersion: 1.9.0
