# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: WDev.ConTeXtIDE
PackageVersion: 1.5.0.0
PackageLocale: en-US
Publisher: WDev
PublisherUrl: https://github.com/WelterDevelopment
PublisherSupportUrl: https://github.com/WelterDevelopment/ConTeXt-IDE-WinUI/issues
PackageName: ConTeXt IDE
PackageUrl: https://github.com/WelterDevelopment/ConTeXt-IDE-WinUI
License: Proprietary
ShortDescription: Simple and self-contained IDE for the ConTeXt typesetting system.
Tags:
- csharp
- net5
- tex
- tex-context
ReleaseNotesUrl: https://github.com/WelterDevelopment/ConTeXt-IDE-WinUI/releases/tag/1.5.0
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/WelterDevelopment/ConTeXt-IDE-WinUI/wiki
ManifestType: defaultLocale
ManifestVersion: 1.9.0
